language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - sudo apt-get update
    - sudo apt-get install -qq protobuf-compiler
services:
    - riak
install:
    - pip install -e . --use-mirrors
script: python setup.py nosetests
